image: Visual Studio 2022

branches:
  except:
  - /^experimental.*$/

skip_tags: true

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
  - dotnet --info
  - dotnet tool install --global codecov.tool

build_script:
  - dotnet build Remote.Linq.sln -c Release
  - dotnet build Remote.Linq.Samples.sln

test_script:
  - dotnet test Remote.Linq.sln --settings coverlet.runsettings

after_test:
  - codecov -f **\coverage.cobertura.xml
