language: generic

branches:
  except:
  - experimental

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      env: FRAMEWORK_VERSION=3.0 CLI_VERSION=Latest CONFIGURATION=Release
    - os: osx
      env: FRAMEWORK_VERSION=3.0 CLI_VERSION=Latest CONFIGURATION=Release

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL "https://dot.net/v1/dotnet-install.sh" | bash /dev/stdin --channel 3.0 --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

before_script:
  - if test "$TRAVIS_OS_NAME" == "osx"; then export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib; fi
  - dotnet --info

script:
  # tests
  - travis_wait 20 dotnet test test/Remote.Linq.Tests -c $CONFIGURATION -f "netcoreapp$FRAMEWORK_VERSION"
  - dotnet test test/Remote.Linq.EntityFrameworkCore.Tests -c $CONFIGURATION -f "netcoreapp$FRAMEWORK_VERSION"
  # samples
  #WCF- dotnet build samples/QueryDemo
  #WCF- dotnet build samples/RemoteQueryable/0_Basic
  #WCF- dotnet build samples/RemoteQueryable/1_Async
  #WCF- dotnet build samples/RemoteQueryable/2_DynamicObjectWithKnownTypes
  #WCF- dotnet build samples/RemoteQueryable/3_KnownTypesAsObjects
  #WCF- dotnet build samples/RemoteQueryable/4_CustomTypeResolver
  #WCF- dotnet build samples/RemoteQueryable/5_ServerDefinedProjection
  #WCF- dotnet build samples/RemoteQueryable/6_Compression
  #WCF- dotnet build samples/RemoteQueryable/7_Inheritance
  - dotnet build samples/RemoteQueryable/10_UsingBinarySerializationOverTcp
  - dotnet build samples/RemoteQueryable/10_UsingJsonSerializationOverTcp
  #WebAPI- dotnet build samples/RemoteQueryable/10_UsingJsonSerializationOverWebApi
  - dotnet build samples/RemoteQueryable/10_UsingXmlSerializationOverHttp
  - dotnet build samples/RemoteQueryable/10_UsingXmlSerializationOverTcp
  #WebAPI- dotnet build samples/RemoteQueryable/10_UsingXmlSerializationOverWebApi
  #WCF- dotnet build samples/RemoteQueryableToEntityFramework
  #WCF- dotnet build samples/RemoteQueryableToEntityFrameworkCore
  #WCF- dotnet build samples/RemoteQueryableToNHibernate