sudo: required
services:
  - docker  
language: csharp
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g 
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL "https://raw.githubusercontent.com/dotnet/cli/release/3.0.1xx/scripts/obtain/dotnet-install.sh" | bash /dev/stdin --version "3.0.100" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH" 
before_script:  
  - dotnet --info
script:
  #WCF- dotnet build ./QueryDemo/QueryDemo.sln
  #WCF- dotnet build ./RemoteQueryable/0_Basic/RemoteQueryable_Basic.sln
  #WCF- dotnet build ./RemoteQueryable/1_Async/RemoteQueryable_Async.sln
  #WCF- dotnet build ./RemoteQueryable/2_DynamicObjectWithKnownTypes/RemoteQueryable_DynamicObjectWithKnownTypes.sln
  #WCF- dotnet build ./RemoteQueryable/3_KnownTypesAsObjects/RemoteQueryable_KnownTypesAsObjects.sln
  #WCF- dotnet build ./RemoteQueryable/4_CustomTypeResolver/RemoteQueryable_CustomTypeResolver.sln
  #WCF- dotnet build ./RemoteQueryable/5_ServerDefinedProjection/RemoteQueryable_ServerDefinedProjection.sln
  #WCF- dotnet build ./RemoteQueryable/6_Compression/RemoteQueryable_Compression.sln
  #WCF- dotnet build ./RemoteQueryable/7_Inheritance/RemoteQueryable_Inheritance.sln
  - dotnet build ./RemoteQueryable/10_UsingBinarySerializationOverTcp/RemoteQueryable_UsingBinarySerializationOverTcp.sln
  - dotnet build ./RemoteQueryable/10_UsingJsonSerializationOverTcp/RemoteQueryable_UsingJsonSerializationOverTcp.sln
  #WebAPI- dotnet build ./RemoteQueryable/10_UsingJsonSerializationOverWebApi/RemoteQueryable_UsingJsonSerializationOverWebApi.sln
  - dotnet build ./RemoteQueryable/10_UsingXmlSerializationOverHttp/RemoteQueryable_UsingXmlSerializationOverHttp.sln
  - dotnet build ./RemoteQueryable/10_UsingXmlSerializationOverTcp/RemoteQueryable_UsingXmlSerializationOverTcp.sln
  #WebAPI- dotnet build ./RemoteQueryable/10_UsingXmlSerializationOverWebApi/RemoteQueryable_UsingXmlSerializationOverWebApi.sln
  #WCF- dotnet build ./RemoteQueryableToEntityFramework/RemoteQueryableToEntityFramework.sln
  #WCF- dotnet build ./RemoteQueryableToEntityFrameworkCore/RemoteQueryableToEntityFrameworkCore.sln
  #WCF- dotnet build ./RemoteQueryableToNHibernate/RemoteQueryableToNHibernate.sln