sudo: required
services:
  - docker  
language: csharp
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g 
install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL "https://raw.githubusercontent.com/dotnet/cli/2.0.0/scripts/obtain/dotnet-install.sh" | bash /dev/stdin --version "2.0.0" --install-dir "/.dotnetcli"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH" 
before_script:  
  - dotnet --info
  - nuget restore ./QueryDemo/QueryDemo.sln
  - nuget restore ./RemoteQueryable/0_Basic/RemoteQueryable_Basic.sln
  - nuget restore ./RemoteQueryable/1_Async/RemoteQueryable_Async.sln
  - nuget restore ./RemoteQueryable/2_DynamicObjectWithKnownTypes/RemoteQueryable_DynamicObjectWithKnownTypes.sln
  - nuget restore ./RemoteQueryable/3_KnownTypesAsObjects/RemoteQueryable_KnownTypesAsObjects.sln
  - nuget restore ./RemoteQueryable/4_CustomTypeResolver/RemoteQueryable_CustomTypeResolver.sln
  - nuget restore ./RemoteQueryable/5_ServerDefinedProjection/RemoteQueryable_ServerDefinedProjection.sln
  - nuget restore ./RemoteQueryable/6_Compression/RemoteQueryable_Compression.sln
  - nuget restore ./RemoteQueryable/7_Inheritance/RemoteQueryable_Inheritance.sln
  - nuget restore ./RemoteQueryable/10_UsingBinarySerializationOverTcp/RemoteQueryable_UsingBinarySerializationOverTcp.sln
  - nuget restore ./RemoteQueryable/10_UsingJsonSerializationOverTcp/RemoteQueryable_UsingJsonSerializationOverTcp.sln
  - nuget restore ./RemoteQueryable/10_UsingJsonSerializationOverWebApi/RemoteQueryable_UsingJsonSerializationOverWebApi.sln
  - nuget restore ./RemoteQueryable/10_UsingXmlSerializationOverHttp/RemoteQueryable_UsingXmlSerializationOverHttp.sln
  - nuget restore ./RemoteQueryable/10_UsingXmlSerializationOverTcp/RemoteQueryable_UsingXmlSerializationOverTcp.sln
  - nuget restore ./RemoteQueryable/10_UsingXmlSerializationOverWebApi/RemoteQueryable_UsingXmlSerializationOverWebApi.sln
  - nuget restore ./RemoteQueryableToEntityFramework/RemoteQueryableToEntityFramework.sln
  - nuget restore ./RemoteQueryableToNHibernate/RemoteQueryableToNHibernate.sln
script:
  - dotnet build --configuration Release ./QueryDemo/QueryDemo.sln
  - dotnet build --configuration Release ./RemoteQueryable/0_Basic/RemoteQueryable_Basic.sln
  - dotnet build --configuration Release ./RemoteQueryable/1_Async/RemoteQueryable_Async.sln
  - dotnet build --configuration Release ./RemoteQueryable/2_DynamicObjectWithKnownTypes/RemoteQueryable_DynamicObjectWithKnownTypes.sln
  - dotnet build --configuration Release ./RemoteQueryable/3_KnownTypesAsObjects/RemoteQueryable_KnownTypesAsObjects.sln
  - dotnet build --configuration Release ./RemoteQueryable/4_CustomTypeResolver/RemoteQueryable_CustomTypeResolver.sln
  - dotnet build --configuration Release ./RemoteQueryable/5_ServerDefinedProjection/RemoteQueryable_ServerDefinedProjection.sln
  - dotnet build --configuration Release ./RemoteQueryable/6_Compression/RemoteQueryable_Compression.sln
  - dotnet build --configuration Release ./RemoteQueryable/7_Inheritance/RemoteQueryable_Inheritance.sln
  - dotnet build --configuration Release ./RemoteQueryable/10_UsingBinarySerializationOverTcp/RemoteQueryable_UsingBinarySerializationOverTcp.sln
  - dotnet build --configuration Release ./RemoteQueryable/10_UsingJsonSerializationOverTcp/RemoteQueryable_UsingJsonSerializationOverTcp.sln
  - dotnet build --configuration Release ./RemoteQueryable/10_UsingJsonSerializationOverWebApi/RemoteQueryable_UsingJsonSerializationOverWebApi.sln
  - dotnet build --configuration Release ./RemoteQueryable/10_UsingXmlSerializationOverHttp/RemoteQueryable_UsingXmlSerializationOverHttp.sln
  - dotnet build --configuration Release ./RemoteQueryable/10_UsingXmlSerializationOverTcp/RemoteQueryable_UsingXmlSerializationOverTcp.sln
  - dotnet build --configuration Release ./RemoteQueryable/10_UsingXmlSerializationOverWebApi/RemoteQueryable_UsingXmlSerializationOverWebApi.sln
  - dotnet build --configuration Release ./RemoteQueryableToEntityFramework/RemoteQueryableToEntityFramework.sln
  - dotnet build --configuration Release ./RemoteQueryableToEntityFrameworkCore/RemoteQueryableToEntityFrameworkCore.sln
  - dotnet build --configuration Release ./RemoteQueryableToNHibernate/RemoteQueryableToNHibernate.sln