language: minimal

if: tag IS blank

branches:
  except:
  - /^experimental.*$/

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      env: CONFIGURATION=Release
    - os: osx
      osx_image: xcode14.2 # https://docs.travis-ci.com/user/reference/osx/#macos-version
      env: CONFIGURATION=Release

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0 --version latest --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
  - if test "$TRAVIS_OS_NAME" == "osx"; then export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib; fi

before_script:
  - dotnet --info

script:
  - dotnet test Remote.Linq.sln -c $CONFIGURATION -f net9.0
