language: csharp
mono: none
dotnet: 5.0.102

branches:
  except:
  - /^experimental.*$/
  - 6.3.x

matrix:
  include:
    - os: linux
      env: CONFIGURATION=Release
    - os: osx
      env: CONFIGURATION=Release

before_script:
  - dotnet --info

script:
  - travis_wait 20 dotnet test test/Remote.Linq.Tests      -c $CONFIGURATION -f net5.0
  - dotnet test test/Remote.Linq.Async.Queryable.Tests     -c $CONFIGURATION -f net5.0
  - dotnet test test/Remote.Linq.EntityFramework.Tests     -c $CONFIGURATION -f net5.0
  - dotnet test test/Remote.Linq.EntityFrameworkCore.Tests -c $CONFIGURATION -f net5.0