language: generic  

branches:
  except:
  - experimental

addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Debug CLI_VERSION=1.0.1
    - os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Release CLI_VERSION=1.0.1
    - os: osx
      env: CONFIGURATION=Debug CLI_VERSION=1.0.1
    - os: osx
      env: CONFIGURATION=Release CLI_VERSION=1.0.1

before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; fi

install:  
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.1/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH" 

before_script:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib; fi
  - dotnet --info

script: 
  - dotnet restore
  - dotnet build ./src/Remote.Linq -c $CONFIGURATION -f netstandard1.6
  - dotnet build ./src/Remote.Linq.Newtonsoft.Json -c $CONFIGURATION -f netstandard1.6
  - dotnet test ./test/Remote.Linq.Tests/Remote.Linq.Tests.csproj -c $CONFIGURATION -f netcoreapp1.0