language: generic  

branches:
  except:
  - experimental

addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      env: FRAMEWORK_VERSION=2.2 CLI_VERSION=2.1.4 CONFIGURATION=Debug
    - os: linux
      env: FRAMEWORK_VERSION=2.2 CLI_VERSION=Latest CONFIGURATION=Release
    - os: osx
      env: FRAMEWORK_VERSION=2.2 CLI_VERSION=2.1.4 CONFIGURATION=Debug
    - os: osx
      env: FRAMEWORK_VERSION=2.2 CLI_VERSION=Latest CONFIGURATION=Release

install:  
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL "https://dot.net/v1/dotnet-install.sh" | bash /dev/stdin --channel 2.2 --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH" 

before_script:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib; fi
  - dotnet --info

script: 
  - dotnet test ./test/Remote.Linq.Tests/Remote.Linq.Tests.csproj -c $CONFIGURATION -f "netcoreapp$FRAMEWORK_VERSION"
  - dotnet test ./test/Remote.Linq.EntityFrameworkCore.Tests/Remote.Linq.EntityFrameworkCore.Tests.csproj -c $CONFIGURATION -f "netcoreapp$FRAMEWORK_VERSION"