language: generic

branches:
  except:
  - experimental

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      env: FRAMEWORK_VERSION=3.1 CLI_VERSION=Latest CONFIGURATION=Release
    - os: osx
      env: FRAMEWORK_VERSION=3.1 CLI_VERSION=Latest CONFIGURATION=Release

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL "https://dot.net/v1/dotnet-install.sh" | bash /dev/stdin --channel 3.1 --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

before_script:
  - if test "$TRAVIS_OS_NAME" == "osx"; then export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib; fi
  - dotnet --info

script:
  # tests
  - travis_wait 20 dotnet test test/Remote.Linq.Tests      -c $CONFIGURATION -f "netcoreapp$FRAMEWORK_VERSION"
  - dotnet test test/Remote.Linq.EntityFramework.Tests     -c $CONFIGURATION -f "netcoreapp$FRAMEWORK_VERSION"
  - dotnet test test/Remote.Linq.EntityFrameworkCore.Tests -c $CONFIGURATION -f "netcoreapp$FRAMEWORK_VERSION"
  # samples
  #WCF- dotnet build samples/QueryDemov
  #WCF- dotnet build samples/RemoteQueryable/00_Basic
  #WCF- dotnet build samples/RemoteQueryable/01_Async
  #WCF- dotnet build samples/RemoteQueryable/02_DynamicObjectWithKnownTypes
  #WCF- dotnet build samples/RemoteQueryable/03_CustomResultHandler
  #WCF- dotnet build samples/RemoteQueryable/04_CustomTypeResolver
  #WCF- dotnet build samples/RemoteQueryable/05_ServerDefinedProjection
  #WCF- dotnet build samples/RemoteQueryable/06_Compression
  #WCF- dotnet build samples/RemoteQueryable/07_Inheritance
  - dotnet build samples/RemoteQueryable/10_UsingBinarySerializationOverTcp
  - dotnet build samples/RemoteQueryable/11_UsingBinarySerializationOverTcpAsync
  - dotnet build samples/RemoteQueryable/12_UsingJsonSerializationOverTcp
  - dotnet build samples/RemoteQueryable/13_UsingJsonSerializationOverTcpAsync
  #WebAPI- dotnet build samples/RemoteQueryable/14_UsingJsonSerializationOverWebApi
  #WebAPI- dotnet build samples/RemoteQueryable/15_UsingXmlSerializationOverHttp
  - dotnet build samples/RemoteQueryable/16_UsingXmlSerializationOverTcp
  #WebAPI- dotnet build samples/RemoteQueryable/17_UsingXmlSerializationOverWebApi
  #WCF- dotnet build samples/RemoteQueryableToEntityFramework
  #WCF- dotnet build samples/RemoteQueryableToEntityFrameworkCore
  #WCF- dotnet build samples/RemoteQueryableToNHibernate
  #.NET- dotnet build samples/SandboxedServer