image: Visual Studio 2019

branches:
  except:
  - experimental

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
  - dotnet --info
  - dotnet restore
  - dotnet tool install --global codecov.tool

build_script:
  - dotnet build src\Remote.Linq
  - dotnet build src\Remote.Linq.EntityFramework
  - dotnet build src\Remote.Linq.EntityFrameworkCore
  - dotnet build src\Remote.Linq.Newtonsoft.Json
  - dotnet build test\Remote.Linq.Tests
  - dotnet build test\Remote.Linq.EntityFramework.Tests
  - dotnet build test\Remote.Linq.EntityFrameworkCore.Tests

test_script:
  - dotnet test test\Remote.Linq.Tests
  - dotnet test test\Remote.Linq.EntityFramework.Tests
  - dotnet test test\Remote.Linq.EntityFrameworkCore.Tests

after_test:
  - dotnet test test\Remote.Linq.Tests                     -f netcoreapp3.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory TestResults
  - dotnet test test\Remote.Linq.EntityFrameworkCore.Tests -f netcoreapp3.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory TestResults
  - codecov -f **\coverage.cobertura.xml

build:
  verbosity: normal