image: Visual Studio 2019

branches:
  except:
  - experimental

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
  - dotnet --info
  - dotnet restore
  - dotnet tool install --global codecov.tool

build_script:
  # framework
  - dotnet build src\Remote.Linq
  - dotnet build src\Remote.Linq.EntityFramework
  - dotnet build src\Remote.Linq.EntityFrameworkCore
  - dotnet build src\Remote.Linq.Newtonsoft.Json
  # tests
  - dotnet build test\Remote.Linq.Tests
  - dotnet build test\Remote.Linq.EntityFramework.Tests
  - dotnet build test\Remote.Linq.EntityFrameworkCore.Tests
  # samples
  - dotnet build samples\QueryDemo
  - dotnet build samples\RemoteQueryable\0_Basic
  - dotnet build samples\RemoteQueryable\1_Async
  - dotnet build samples\RemoteQueryable\2_DynamicObjectWithKnownTypes
  - dotnet build samples\RemoteQueryable\3_KnownTypesAsObjects
  - dotnet build samples\RemoteQueryable\4_CustomTypeResolver
  - dotnet build samples\RemoteQueryable\5_ServerDefinedProjection
  - dotnet build samples\RemoteQueryable\6_Compression
  - dotnet build samples\RemoteQueryable\7_Inheritance
  - dotnet build samples\RemoteQueryable\10_UsingBinarySerializationOverTcp
  - dotnet build samples\RemoteQueryable\10_UsingJsonSerializationOverTcp
  - dotnet build samples\RemoteQueryable\10_UsingJsonSerializationOverWebApi
  - dotnet build samples\RemoteQueryable\10_UsingXmlSerializationOverHttp
  - dotnet build samples\RemoteQueryable\10_UsingXmlSerializationOverTcp
  - dotnet build samples\RemoteQueryable\10_UsingXmlSerializationOverWebApi
  - dotnet build samples\RemoteQueryableToEntityFramework
  - dotnet build samples\RemoteQueryableToEntityFrameworkCore
  - dotnet build samples\RemoteQueryableToNHibernate
  - dotnet build samples\SandboxedQueryServer

test_script:
  - dotnet test test\Remote.Linq.Tests
  - dotnet test test\Remote.Linq.EntityFramework.Tests
  - dotnet test test\Remote.Linq.EntityFrameworkCore.Tests

after_test:
  - dotnet test test\Remote.Linq.Tests                     -f netcoreapp3.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings        --results-directory TestResults
  - dotnet test test\Remote.Linq.EntityFrameworkCore.Tests -f netcoreapp3.0 --collect:"XPlat Code Coverage" --settings coverlet.efcore.runsettings --results-directory TestResults
  - codecov -f **\coverage.cobertura.xml

build:
  verbosity: normal