image: Visual Studio 2017

branches:
  except:
  - experimental

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

before_build:
  - dotnet --info
  - dotnet restore

build_script:
  - dotnet build src\Remote.Linq 
  - dotnet build src\Remote.Linq.Newtonsoft.Json
  - dotnet build test\Remote.Linq.Tests

test_script:
  dotnet test test\Remote.Linq.Tests\Remote.Linq.Tests.csproj

build:
  verbosity: normal