image: Visual Studio 2019

branches:
  except:
  - experimental

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
  - dotnet --info
  - dotnet restore Remote.Linq.sln
  - dotnet restore Remote.Linq.Samples.sln
  - dotnet tool install --global codecov.tool

build_script:
  - dotnet build Remote.Linq.sln
  - dotnet build Remote.Linq.Samples.sln

test_script:
  - dotnet test test\Remote.Linq.Tests
  - dotnet test test\Remote.Linq.Async.Queryable.Tests
  - dotnet test test\Remote.Linq.EntityFramework.Tests
  - dotnet test test\Remote.Linq.EntityFrameworkCore.Tests

after_test:
  - dotnet test test\Remote.Linq.Tests                     -f net5.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings        --results-directory TestResults
  - dotnet test test\Remote.Linq.Async.Queryable.Tests     -f net5.0 --collect:"XPlat Code Coverage" --settings coverlet.efcore.runsettings --results-directory TestResults
  - dotnet test test\Remote.Linq.EntityFrameworkCore.Tests -f net5.0 --collect:"XPlat Code Coverage" --settings coverlet.efcore.runsettings --results-directory TestResults
  - codecov -f **\coverage.cobertura.xml
